# 检测配置
check_path:    
    level: all                      # 检测的等级，选择下面的一种: all  或 warning, style
    root_path:  ./                  # 根目录, 不填默认为当前执行命令的路径
    ########以下需要填写root-path的相对路径########
    include_path:                   # 需要检查的目录数组，会检测check-path列举的每个路径下的所有文件
                                    # 若内容为空则检测 $root_path下所有文件
        ############ 举例############
        # - Application             # 检测Application下的文件
        ############################
        # 添加你的配置：

    nocheck_path:                   # 不需要检测的目录数组, 不填默认为空

        ############ 举例############
        # - a                      # 不检测$root_path/a下的文件
        ############################
        # 添加你的配置：

    ########################################


# 检测结果路径
output_path:    ./check_results    # 输出目录相关配置，可以为绝对路径

# 屏蔽规则
suppress: suppressions.txt          # 当前配置仅使用的抑制规则文件名，抑制规则文件应该存储在 工具安装路径/misra下

# 检测的文件类型
file_types:
    - .h
    - .hpp
    - .c
    - .cpp
    - .cc
    - .ccc





  


