# 检测配置
check_path:    
    level: all                      # 检测的等级，选择下面的一种
                                    # all
                                    # warning, style 
    root_path:  ./                  # 根目录, 不填默认为当前执行命令的路径

# 检测结果路径
output_path:    ./check_results     # 输出目录相关配置

# 屏蔽规则
# 移植文件使用的抑制规则文件名，其应该存储在 工具安装路径/misra下
suppress: suppressions.txt

# 检测的文件类型
file_types:
    - .h
    - .hpp
    - .c
    - .cpp
    - .cc
    - .ccc





  
