# 检测配置
check_path:    
    level: all                       # 检测的等级，选择下面的一种
                                     # all
                                     # warning, style 

    root_path:  ./                   # 根目录, 支持绝对路径和相对路径
    ######################################## 以下需要root-path的相对路径 
    include_path:                    # 需要检查的目录数组，会检测check-path列举的每个路径下的所有文件, 内容为空则检测$root_path所有文件
        # - Application/XCall          # 检测 $root_path/Application下所有文件
        # - b.c
    nocheck_path:                    # 不需要检测的目录/文件数组, 不填默认为空
        # - a.c
        # - src
    ########################################


# 检测结果路径
output_path:    ./check_results                         # 输出目录相关配置

# 屏蔽规则, 此处仅填写抑制规则文件名，其应该存储在工具安装路径/misra下，或安装之前处于安装包的misra目录下
suppress: suppressions.txt       

# 检测的文件类型
file_types:
    - .h
    - .hpp
    - .c
    - .cpp
    - .cc
    - .ccc





  
